name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to AWS CodeDeploy
      uses: aws-actions/aws-codedeploy@v2
      with:
        application-name: ramyacode-deploy
        deployment-group: cd-r
        region: us-east-1
      env:
        AWS_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ AKIAW3MEAPIONHG2JZ7S }}
        AWS_SECRET_ACCESS_KEY: ${{ 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 }}